esphome:
  name: mvhr
  friendly_name: Titon MVHR

esp8266:
  board: d1_mini

# Enable logging (inc. responses from MVHR Unit)
logger:
  level: DEBUG
  logs:
    uart: DEBUG
  baud_rate: 0  # Disables ESPHome serial logging (avoids UART conflicts)

# Enable Home Assistant API
api:
  encryption:
    key: ****

ota:
  - platform: esphome
    password: ****

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mvhr Fallback Hotspot"
    password: ****

captive_portal:

# UART for RS-485 communication
uart:
  id: uart_bus
  tx_pin: 1  # TX (GPIO1)
  rx_pin: 3  # RX (GPIO3)
  baud_rate: 1200
  parity: NONE
  stop_bits: 1
  debug:
    direction: BOTH
  
# Sensors Various (inc Logger)
sensor:
